const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const output = path.join(root, 'dist');

/* Publication boundary: copy only public website assets, never project documents or responses. */
if (fs.existsSync(output)) {
  const marker = path.join(output, '.generated-site-output');
  if (!fs.existsSync(marker)) throw new Error('dist already exists without the generated-output marker. Review it before packaging.');
  fs.rmSync(output, { recursive: true, force: true });
}
fs.mkdirSync(output);
fs.writeFileSync(path.join(output, '.generated-site-output'), 'Generated by scripts/package-site.cjs\n');
for (const file of ['index.html', '404.html', '_redirects', '_headers', 'robots.txt', 'sitemap.xml']) {
  fs.copyFileSync(path.join(root, file), path.join(output, file));
}

/* Copy approved asset extensions only; hidden files, symlinks and backups are excluded. */
function copyPublicTree(directory, extensions) {
  function copy(relative) {
    for (const entry of fs.readdirSync(path.join(root, relative), { withFileTypes: true })) {
      if (entry.name.startsWith('.') || entry.isSymbolicLink()) continue;
      const file = path.join(relative, entry.name);
      if (entry.isDirectory()) copy(file);
      else if (entry.isFile() && extensions.includes(path.extname(entry.name).toLowerCase())) {
        fs.mkdirSync(path.dirname(path.join(output, file)), { recursive: true });
        fs.copyFileSync(path.join(root, file), path.join(output, file));
      }
    }
  }
  copy(directory);
}
copyPublicTree('html', ['.html']);
copyPublicTree('css', ['.css']);
copyPublicTree('js', ['.js', '.mjs']);
copyPublicTree('img', ['.avif', '.webp', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico', '.woff', '.woff2']);

/* Browser data is explicitly public; caches and raw exports are not deployment assets. */
fs.mkdirSync(path.join(output, 'data'));
for (const file of ['clubs.json', 'sports.json']) {
  fs.copyFileSync(path.join(root, 'data', file), path.join(output, 'data', file));
}
console.log('Prepared dist: public pages, assets, club data and Netlify routing/security files.');
